#pragma once

#include "appendix_a6_heat.hpp"
#include "appendix_a7_heat_compensation.hpp"

#include <array>
#include <cmath>
#include <cstddef>
#include <stdexcept>

namespace nsblowup {

struct AppendixA7ScaledMomentChange {
    double Cp{};
    double S{};
    double I{};
};

// Natural-scale conversion for the second A.9 reserved patch.  If
// X=X_* x and E=e_* e(x), then
//   Cp ~ e_*^2, S ~ X_* e_*^2, I ~ X_*^(3/2) e_*.
inline AppendixA7ScaledMomentChange appendix_a7_scale_change(
    const AppendixA7MomentChange& q, double Xstar, double estar) {
    if (!(Xstar > 0.0 && estar > 0.0))
        throw std::invalid_argument("A.7 scales must be positive");
    return {estar * estar * q.Cp,
            Xstar * estar * estar * q.S,
            std::pow(Xstar, 1.5) * estar * q.I};
}

inline AppendixA7MomentChange appendix_a7_unscale_change(
    const AppendixA7ScaledMomentChange& q, double Xstar, double estar) {
    if (!(Xstar > 0.0 && estar > 0.0))
        throw std::invalid_argument("A.7 scales must be positive");
    return {q.Cp / (estar * estar),
            q.S / (Xstar * estar * estar),
            q.I / (std::pow(Xstar, 1.5) * estar)};
}

// Moment discrepancy generated by replacing an E_pow tail by (A.39).
// Work in x=X/X_K.  The caller supplies the dimensionless onset X_K appearing
// in H(2(1-eta^2)/X); this keeps the exponentially large physical X_K out of
// floating-point arithmetic while preserving the exact normalized integrals.
inline AppendixA7MomentChange appendix_a7_heat_tail_discrepancy_normalized(
    double eta, double h, double XK,
    double y_max = 36.0, std::size_t panels = 4096) {
    if (std::abs(eta) > 1.0) throw std::invalid_argument("|eta| must not exceed 1");
    if (!(h > 0.0 && h < 0.5)) throw std::invalid_argument("h must lie in (0,1/2)");
    if (!(XK > 0.0 && y_max > 1.0)) throw std::invalid_argument("invalid tail scale/window");
    if (panels < 2) panels = 2;
    if (panels % 2) ++panels;

    const double dy = y_max / static_cast<double>(panels);
    AppendixA7MomentChange out;
    auto sample = [&](double y) {
        const double x = std::exp(y);
        const double ratio = appendix_a6_terminal_replacement_ratio(y, XK * x, eta, h);
        const double e0 = std::pow(x, -0.5 - h);
        const double de = e0 * (ratio - 1.0);
        const double dE2 = 2.0 * e0 * de + de * de;
        // dX=X_K dx and dx=x dy.  Cp's 1/X cancels x; S and I retain it.
        return std::array<double,3>{0.5 * dE2,
                                    -0.5 * dE2 * x,
                                    std::sqrt(2.0 * x) * de * x};
    };
    std::array<double,3> sum{};
    for (std::size_t i=0; i<=panels; ++i) {
        const double y = static_cast<double>(i) * dy;
        const auto v = sample(y);
        const double w = (i==0 || i==panels) ? 1.0 : (i%2 ? 4.0 : 2.0);
        for (std::size_t k=0;k<3;++k) sum[k] += w*v[k];
    }
    out.Cp = sum[0]*dy/3.0;
    out.S  = sum[1]*dy/3.0;
    out.I  = sum[2]*dy/3.0;
    return out;
}

struct AppendixA7FullScheduleResult {
    AppendixA7MomentChange heat_discrepancy{};
    AppendixA7MomentChange compensation{};
    AppendixA7MomentChange residual{};
    Vector coefficients{};
};

// End-to-end normalized A.7 coupling: compute the actual heat-tail discrepancy
// and ask the second reserved patch to cancel it.  The conversion between the
// tail and patch natural scales is explicit so the same routine can be fed the
// real A.2/A.3 schedule scales once they are exposed by the schedule object.
inline AppendixA7FullScheduleResult appendix_a7_couple_heat_to_reserved_patch(
    double eta, double lambda, double h, double XK,
    double Xpatch_over_XK, double epatch_over_eK,
    double y_max = 36.0, std::size_t panels = 4096) {
    if (!(Xpatch_over_XK > 0.0 && epatch_over_eK > 0.0))
        throw std::invalid_argument("relative patch scales must be positive");

    const auto heat = appendix_a7_heat_tail_discrepancy_normalized(
        eta,h,XK,y_max,panels);

    // Heat discrepancy is expressed in tail natural scales (XK,eK). Convert
    // it to the patch's natural units before solving c -> (Cp,S,I).
    AppendixA7ScaledMomentChange heat_phys{heat.Cp, heat.S, heat.I};
    const auto target_patch = appendix_a7_unscale_change(
        {-heat_phys.Cp,-heat_phys.S,-heat_phys.I},
        Xpatch_over_XK, epatch_over_eK);

    AppendixA7HeatCompensation solver(eta,lambda,panels);
    const Vector c = solver.solve_for_change(target_patch.vector());
    const auto comp_patch = solver.change(c);
    const auto comp_tail_scaled = appendix_a7_scale_change(
        comp_patch,Xpatch_over_XK,epatch_over_eK);
    AppendixA7MomentChange comp_tail{comp_tail_scaled.Cp,comp_tail_scaled.S,comp_tail_scaled.I};

    AppendixA7FullScheduleResult out;
    out.heat_discrepancy=heat;
    out.compensation=comp_tail;
    out.residual={heat.Cp+comp_tail.Cp,
                  heat.S+comp_tail.S,
                  heat.I+comp_tail.I};
    out.coefficients=c;
    return out;
}

} // namespace nsblowup
